### PR TITLE
Track readme files for multi-content repositories

### PR DESCRIPTION
**Pull request by cutwater**

### CODE REVIEW

**Comment by chouseknecht** [comment]
Fixes #477

**Comment by chouseknecht** [comment]
@cutwater 

I'd like to test this, before we merge it. Will try to test it ASAP. 

It may break some things in the UI, which is perfectly fine, but I'd like to document what they are, and make sure I track and resolve them.

**Comment by chouseknecht** [comment]
Import of `atestuseraccount/ansible-testing-content` resulted in the following traceback:

https://gist.github.com/chouseknecht/d093f876185d0e6c4f506b913995573c

**Comment by cutwater** [comment]
@chouseknecht checking

**Comment by cutwater** [comment]
@chouseknecht I checked on a empty database. Try recreate your db or let's troubleshoot it together today.

**Comment by cutwater** [comment]
@chouseknecht fixed, please review

**Comment by chouseknecht** [comment]
@cutwater 

Tested locally. Working as expected. Nice job!

**Pull request merged**
