### PR TITLE
My Content UI

### PR DESCRIPTION
**Pull request by cfchase**

### CODE REVIEW

**Comment by chouseknecht** [comment]
@cutwater 

Testing this PR, I'm seeing an import error. Rebased with the latest from `feature/multi-content`, but everything is up to date. 

Here's the traceback:

```
Traceback (most recent call last):
  File "/galaxy/galaxy/main/celerytasks/tasks.py", line 250, in import_repository
    _import_repository(import_task, workdir, logger)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/galaxy/galaxy/main/celerytasks/tasks.py", line 205, in _import_repository
    for loader in repo_loader.load():
TypeError: 'RoleLoader' object is not iterable
```

Testing with `chouseknecht/adb-up-role`: 

desktop

**Comment by chouseknecht** [comment]
@cfcahse: 

The UI is looking great!

The only thing that would be nice to have is tooltips on the buttons. For example, the primary `Add` button vs `Add Content`, it would be nice to hover over each, and see a short description of the action.

**Comment by cfchase** [comment]
@chouseknecht Added uib-tooltips where I could.  In the case of "Add Content" it's still a title, which is super slow to show the tooltip, but it's under control of the pfListView, so I'm not sure how to control that just yet.  I also added a Delete spinner.

**Comment by cutwater** [comment]
@chouseknecht fixed `ImportError` in https://github.com/ansible/galaxy/pull/340

**Pull request merged**
