### PR TITLE
Fix GitHub avatar sizing

### PR DESCRIPTION
**Pull request by jawyoonis**
issue #1170
- I changed the size of Red Ansible logo to fit the page and clear 
-also added object-fit to search and author details page

### CODE REVIEW

**Comment by cutwater** [comment]
@jawyoonis Thank you for your PR. Please use more descriptive name for your PR.

**Comment by chouseknecht** [comment]
@davidn rebasing fixed this. `yarn.lock` is no longer in the list of modified files.

**Comment by chouseknecht** [comment]
@cutwater made the title more descriptive

**Comment by chouseknecht** [comment]
@newswangerd Removed `overflow: hidden` on image containers, and that seemed to fix it. 

Here's what I'm seeing locally:

overflow

**Comment by chouseknecht** [comment]
I think this is good to go. For some reason GitHub webhooks are busted, and Travis CI is not firing. Once we get a clean build, we can merge this. 

@jawyoonis Thanks for working on this!

**Pull request merged**
