### PR TITLE
Add django management command 'show_urls'

### PR DESCRIPTION
**Pull request by cutwater**
Add a django management command 'show_urls' for development
purposes. It displays allconfigured URL patterns and
corresponding view callables.

### CODE REVIEW

**Comment by cchurch** [comment]
Install `django-extensions` and you get the same thing: https://github.com/django-extensions/django-extensions/blob/master/django_extensions/management/commands/show_urls.py

**Comment by cutwater** [comment]
@cchurch Didn't want to bring additional dependency to project for just one function

**Comment by chouseknecht** [comment]
@cutwater 

I think @cchurch is right. Seems like having `django-extensions` installed during development would be really handy. It provides several useful utilities for troubleshooting things. 

Can we add it to our [dev Dockerfile](https://github.com/ansible/galaxy/blob/develop/scripts/docker-dev/Dockerfile), and then add it to installed apps in [settings/development.py](https://github.com/ansible/galaxy/blob/develop/galaxy/settings/development.py)?

**Comment by cutwater** [comment]
@chouseknecht as immediate solution we can add it to dev Dockerfile, but later I'd prefer to have in in `requirements-dev.txt`.

Closing this one.

**Pull request closed without merging**
