### PR TITLE
add documentation guidelines for Galaxy roles

### PR DESCRIPTION
**Pull request by samccann**
Fixes https://github.com/ansible/galaxy/issues/1234

Add a section to the Galaxy contributor docs to cover how to document a role, with some examples.

### CODE REVIEW

**Comment by chouseknecht** [comment]
@samccann 

Not opposed to this. What's the bigger picture though? What do we expect the Galaxy server to do with `docs/*.md`? Do we expect `ansible-doc` to read these files?

**Comment by samccann** [comment]
The attempt here is to put in some guidelines so that we know roles (especially certified roles, as they come in) will have good documentation to go with it.  Longer-term, we need to figure out the strategy as you are suggesting. Personally, yes, I'd like to see `ansible-docs` work for roles as well. I don't know at the moment what that entails, but as roles grow, we want as much documentation support as we have today for modules.  

There is a longer term need to figure out what Galaxy does with those `/md `files. There's another issue related to that which is more of an experiment - [](https://github.com/ansible/galaxy/issues/1236). 
..adding @acozine as well. We are just starting out with thoughts on how Galaxy documentation/information needs to evolve as roles use grows.

**Comment by thaumos** [comment]
Is it possible to have a call about this, @samccann?

I also am interested in having ansible-doc handle collection documentation as well. It's not something on the roadmap right now for Engine, but we can talk about it for later next year. 

I want to understand the choices in doc format type out of curiosity.  Also just hear any other thoughts you all may have on the subject.

**Comment by samccann** [comment]
Sent something to your calendars for later next week. thanks!

**Comment by cutwater** [comment]
@chouseknecht @samccann what is the status of this PR?

**Comment by samccann** [comment]
@cutwater on hold. We just restarted the discussion around what is required for roles documentation. I'm closing this PR for now.

**Pull request closed without merging**
