### PR TITLE
Fix issue 234

### PR DESCRIPTION
**Pull request by MarcusTomlinson**
Fix issue 234 (https://github.com/ansible/galaxy-issues/issues/234)
* Copy package.json to /galaxy to fix ansible_gulp_1 "Install node packages" task.
* Install galaxy egg-info outside of mounted dir to fix ansible_django_1 "galaxy-manage" call.

### CODE REVIEW

**Comment by MarcusTomlinson** [comment]
Has this project been abandoned?

**Comment by chouseknecht** [comment]
@MarcusTomlinson 

Nope. Not abandoned. Just not always a top priority.

I updated the build to use the latest release of Ansible Container. I can build locally, and it works on Travis. Can you confirm whether not you're still seeing an issue. 

Thanks!

**Comment by TemperingPick** [comment]
@chouseknecht 

I can confirm that I'm running into the same error into #234 however, it has to be because something failed when building a container due to a proxy/firewall issue as I can build it fine locally. Will try some things and see what I can do.

**Comment by TemperingPick** [comment]
@chouseknecht 

I can't seem to find where it fails at. Anything that might go out to the internet has the proxies set but looking at the django logs gives me this error:

`/galaxy
12:48:00 system      | celeryd.1 started (pid=60)
12:48:00 system      | runserver.1 started (pid=61)
12:48:01 celeryd.1   | Running a worker with superuser privileges when the
12:48:01 celeryd.1   | worker accepts messages serialized with pickle is a very bad idea!
12:48:01 celeryd.1   |
12:48:01 celeryd.1   | If you really want to continue then you have to set the C_FORCE_ROOT
12:48:01 celeryd.1   | environment variable (but please think about this before you do).
12:48:01 celeryd.1   |
12:48:01 celeryd.1   | User information: uid=1000 euid=1000 gid=0 egid=0
12:48:01 celeryd.1   |
12:48:01 system      | celeryd.1 stopped (rc=1)
12:48:01 system      | sending SIGTERM to runserver.1 (pid 61)
12:48:01 system      | runserver.1 stopped (rc=-15)

PLAY [Database init] ***********************************************************

TASK [Wait for postgresql] *****************************************************
ok: [localhost]

TASK [Perform initial migrations] **********************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/venv/bin/galaxy-manage", "migrate", "--noinput", "--fake-initial"], "delta": "0:00:00.194884", "end": "2017-07-25 13:19:24.892198", "failed": true, "rc": 1, "start": "2017-07-25 13:19:24.697314", "stderr": "Traceback (most recent call last):\n  File \"/venv/bin/galaxy-manage\", line 11, in <module>\n    load_entry_point('galaxy', 'console_scripts', 'galaxy-manage')()\n  File \"build/bdist.linux-x86_64/egg/pkg_resources/__init__.py\", line 561, in load_entry_point\n  File \"build/bdist.linux-x86_64/egg/pkg_resources/__init__.py\", line 2631, in load_entry_point\n  File \"build/bdist.linux-x86_64/egg/pkg_resources/__init__.py\", line 2291, in load\n  File \"build/bdist.linux-x86_64/egg/pkg_resources/__init__.py\", line 2297, in resolve\nImportError: No module named galaxy", "stderr_lines": ["Traceback (most recent call last):", "  File \"/venv/bin/galaxy-manage\", line 11, in <module>", "    load_entry_point('galaxy', 'console_scripts', 'galaxy-manage')()", "  File \"build/bdist.linux-x86_64/egg/pkg_resources/__init__.py\", line 561, in load_entry_point", "  File \"build/bdist.linux-x86_64/egg/pkg_resources/__init__.py\", line 2631, in load_entry_point", "  File \"build/bdist.linux-x86_64/egg/pkg_resources/__init__.py\", line 2291, in load", "  File \"build/bdist.linux-x86_64/egg/pkg_resources/__init__.py\", line 2297, in resolve", "ImportError: No module named galaxy"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/setup/dbinit.retry
`

**Comment by chouseknecht** [comment]
@TemperingPick 

I see now what happened. In the latest version of Ansible Container we were not mounting any volumes during the build process. Because of that `/galaxy` was empty during the build, and no node packages installed. I guess the `npm` module didn't manifest an error for a missing `package.json` file. 

With [this commit](https://github.com/ansible/ansible-container/commit/dd2a6544aedffa5eea1738ad3d9a987bd2c1c04b) in Ansible Container, volumes are now mounted during the build. So now `/galaxy` containers a `package.json` file, and the list of packages gets installed.

Based on this change, restructuring `container.yml` and `gulp-role/tasks/main.yml`, which should make this PR unnecessary.

**Comment by TemperingPick** [comment]
@chouseknecht 

I'm still getting this same error, even with running the latest Ansible Container from the source.

**Comment by chouseknecht** [comment]
@TemperingPick 

I think the error message you're presenting comes from the startup of the django container. Can you make sure that the django image gets rebuilt with the new code. It seems from the error message that galaxy is not getting installed. The very last task in the build process installs galaxy, so I would be curious to know if that worked correctly.

**Comment by chouseknecht** [comment]
@TemperingPick 

I think I've been able to duplicate the error you're seeing. Working on fixing it now...

**Comment by chouseknecht** [comment]
@TemperingPick 

Just pushed changes that *should* fix the error you're hitting.

**Comment by chouseknecht** [comment]
Closing this, as I *think* it's no longer relevant. If I'm wrong, please comment, and I'll re-open. 

Thanks!

**Pull request closed without merging**
